/* ============================================================
   Trivia Quest — categories + question bank
   AUTO-GENERATED from assets/data/questions_source.json
   (run: node tools/build_questions.js) — do not hand-edit.
   Each question: { q, choices:[4], answer:index, d:'easy'|'normal'|'hard' }
   ============================================================ */
window.CATEGORIES = [
  {
    "id": "science",
    "name": "Science",
    "color": "#39C16C",
    "art": "assets/art/characters/science.svg",
    "blurb": "Atoms, space & the natural world"
  },
  {
    "id": "general_knowledge",
    "name": "General",
    "color": "#EC4B57",
    "art": "assets/art/characters/general_knowledge.svg",
    "blurb": "A little bit of everything"
  },
  {
    "id": "art",
    "name": "Arts",
    "color": "#A45BD6",
    "art": "assets/art/characters/arts.svg",
    "blurb": "Painters, styles & masterpieces"
  },
  {
    "id": "geography",
    "name": "Geography",
    "color": "#2E9BD6",
    "art": "assets/art/characters/geography.svg",
    "blurb": "Capitals, rivers & far-off places"
  },
  {
    "id": "sports",
    "name": "Sports",
    "color": "#F3973F",
    "art": "assets/art/characters/sports.svg",
    "blurb": "Champions, rules & records"
  },
  {
    "id": "history",
    "name": "History",
    "color": "#F4C63E",
    "art": "assets/art/characters/history.svg",
    "blurb": "Empires, leaders & turning points"
  }
];

window.QUESTION_BANK = {
  "science": [
    { q:"What is the chemical formula for water?", choices:["H2O","CO2","O2","NaCl"], answer:0, d:"easy" },
    { q:"How many legs does an insect have?", choices:["Four","Six","Eight","Two"], answer:1, d:"easy" },
    { q:"What gas do humans need to breathe to survive?", choices:["Oxygen","Carbon dioxide","Nitrogen","Helium"], answer:0, d:"easy" },
    { q:"What is the center of an atom called?", choices:["Nucleus","Electron","Molecule","Cell"], answer:0, d:"easy" },
    { q:"Which planet is known as the Red Planet?", choices:["Mars","Venus","Jupiter","Saturn"], answer:0, d:"easy" },
    { q:"What is the largest planet in our solar system?", choices:["Jupiter","Saturn","Earth","Neptune"], answer:0, d:"easy" },
    { q:"What process do plants use to make food from sunlight?", choices:["Photosynthesis","Respiration","Digestion","Evaporation"], answer:0, d:"easy" },
    { q:"Which organ pumps blood through your body?", choices:["Heart","Lung","Liver","Brain"], answer:0, d:"easy" },
    { q:"What is frozen water called?", choices:["Ice","Steam","Vapor","Dew"], answer:0, d:"easy" },
    { q:"What is the closest star to Earth?", choices:["The Sun","The Moon","Polaris","Alpha Centauri"], answer:0, d:"easy" },
    { q:"What force pulls objects toward the Earth?", choices:["Gravity","Magnetism","Friction","Tension"], answer:0, d:"easy" },
    { q:"How many planets are in our solar system?", choices:["Seven","Eight","Nine","Ten"], answer:1, d:"easy" },
    { q:"What is the fastest land animal?", choices:["Cheetah","Lion","Horse","Leopard"], answer:0, d:"easy" },
    { q:"What is the largest mammal on Earth?", choices:["Blue whale","Elephant","Giraffe","Hippopotamus"], answer:0, d:"easy" },
    { q:"Which planet do we live on?", choices:["Earth","Mars","Venus","Mercury"], answer:0, d:"easy" },
    { q:"What is the chemical symbol for gold?", choices:["Au","Ag","Gd","Go"], answer:0, d:"easy" },
    { q:"How many colors are in a rainbow?", choices:["Five","Six","Seven","Eight"], answer:2, d:"easy" },
    { q:"What do we call animals that eat only plants?", choices:["Herbivores","Carnivores","Omnivores","Insectivores"], answer:0, d:"easy" },
    { q:"What is the boiling point of water in Celsius?", choices:["Zero","Fifty","One hundred","Two hundred twelve"], answer:2, d:"easy" },
    { q:"Which sense organ do you use to smell?", choices:["Nose","Ear","Eye","Tongue"], answer:0, d:"easy" },
    { q:"What is the chemical symbol for sodium?", choices:["Na","So","Sd","S"], answer:0, d:"normal" },
    { q:"What is the hardest known natural substance?", choices:["Diamond","Gold","Iron","Quartz"], answer:0, d:"normal" },
    { q:"How many bones are in the adult human body?", choices:["201","206","210","196"], answer:1, d:"normal" },
    { q:"Which gas makes up most of Earth's atmosphere?", choices:["Nitrogen","Oxygen","Carbon dioxide","Argon"], answer:0, d:"normal" },
    { q:"The speed of light is approximately how fast?", choices:["3,000 km/s","30,000 km/s","300,000 km/s","3,000,000 km/s"], answer:2, d:"normal" },
    { q:"What is often called the powerhouse of the cell?", choices:["Mitochondria","Nucleus","Ribosome","Golgi apparatus"], answer:0, d:"normal" },
    { q:"Which planet has the most prominent ring system?", choices:["Saturn","Jupiter","Uranus","Neptune"], answer:0, d:"normal" },
    { q:"What is the pH of pure water?", choices:["Zero","Seven","Fourteen","One"], answer:1, d:"normal" },
    { q:"Which blood cells primarily fight infection?", choices:["White blood cells","Red blood cells","Platelets","Plasma"], answer:0, d:"normal" },
    { q:"What is the most common element in the universe?", choices:["Hydrogen","Helium","Oxygen","Carbon"], answer:0, d:"normal" },
    { q:"What type of energy does a moving object have?", choices:["Kinetic","Potential","Thermal","Chemical"], answer:0, d:"normal" },
    { q:"Who proposed the theory of evolution by natural selection?", choices:["Charles Darwin","Isaac Newton","Albert Einstein","Gregor Mendel"], answer:0, d:"normal" },
    { q:"What is the chemical formula for common table salt?", choices:["NaCl","KCl","NaCO3","HCl"], answer:0, d:"normal" },
    { q:"How many chambers does the human heart have?", choices:["Two","Three","Four","Five"], answer:2, d:"normal" },
    { q:"What is the smallest basic unit of life?", choices:["Cell","Atom","Molecule","Organ"], answer:0, d:"normal" },
    { q:"Which scientist developed the three laws of motion?", choices:["Isaac Newton","Galileo Galilei","Albert Einstein","Niels Bohr"], answer:0, d:"normal" },
    { q:"What is the freezing point of water in Fahrenheit?", choices:["Zero","Thirty-two","One hundred","Two hundred twelve"], answer:1, d:"normal" },
    { q:"Which part of the brain controls balance and coordination?", choices:["Cerebellum","Cerebrum","Brainstem","Hippocampus"], answer:0, d:"normal" },
    { q:"Which planet is closest to the Sun?", choices:["Mercury","Venus","Earth","Mars"], answer:0, d:"normal" },
    { q:"What is the process by which a liquid turns into a gas?", choices:["Evaporation","Condensation","Sublimation","Freezing"], answer:0, d:"normal" },
    { q:"What is the most abundant metal in Earth's crust?", choices:["Aluminium","Iron","Copper","Calcium"], answer:0, d:"hard" },
    { q:"What is the atomic number of carbon?", choices:["Four","Six","Eight","Twelve"], answer:1, d:"hard" },
    { q:"Who discovered penicillin?", choices:["Alexander Fleming","Louis Pasteur","Joseph Lister","Robert Koch"], answer:0, d:"hard" },
    { q:"What is the SI unit of electric current?", choices:["Ampere","Volt","Ohm","Watt"], answer:0, d:"hard" },
    { q:"Which metal has the highest melting point of any metal?", choices:["Tungsten","Iron","Platinum","Titanium"], answer:0, d:"hard" },
    { q:"Who is known as the father of the periodic table?", choices:["Dmitri Mendeleev","Niels Bohr","John Dalton","Ernest Rutherford"], answer:0, d:"hard" },
    { q:"Which subatomic particle was discovered by J.J. Thomson?", choices:["Electron","Proton","Neutron","Photon"], answer:0, d:"hard" },
    { q:"What is the chemical symbol for potassium?", choices:["K","P","Po","Pt"], answer:0, d:"hard" },
    { q:"What is Avogadro's number approximately?", choices:["6.022 x 10^23","3.14 x 10^10","1.6 x 10^-19","9.81 x 10^8"], answer:0, d:"hard" },
    { q:"About how many light-years away is the nearest star system, Alpha Centauri?", choices:["1.5","4.4","10","25"], answer:1, d:"hard" }
  ],
  "general_knowledge": [
    { q:"How many days are in a week?", choices:["Five","Six","Seven","Eight"], answer:2, d:"easy" },
    { q:"What is the opposite of 'hot'?", choices:["Cold","Warm","Cool","Mild"], answer:0, d:"easy" },
    { q:"How many minutes are in an hour?", choices:["Thirty","Forty-five","Sixty","Ninety"], answer:2, d:"easy" },
    { q:"What color is the sky on a clear day?", choices:["Blue","Green","Red","Yellow"], answer:0, d:"easy" },
    { q:"How many months are in a year?", choices:["Ten","Eleven","Twelve","Thirteen"], answer:2, d:"easy" },
    { q:"What do cows produce that people drink?", choices:["Milk","Juice","Water","Honey"], answer:0, d:"easy" },
    { q:"Which animal says 'moo'?", choices:["Cow","Dog","Cat","Sheep"], answer:0, d:"easy" },
    { q:"How many sides does a triangle have?", choices:["Three","Four","Five","Six"], answer:0, d:"easy" },
    { q:"What is the first month of the year?", choices:["January","December","March","June"], answer:0, d:"easy" },
    { q:"How many wheels does a standard car have?", choices:["Two","Three","Four","Six"], answer:2, d:"easy" },
    { q:"What do you call a baby dog?", choices:["Puppy","Kitten","Cub","Calf"], answer:0, d:"easy" },
    { q:"Which meal do people typically eat in the morning?", choices:["Breakfast","Lunch","Dinner","Supper"], answer:0, d:"easy" },
    { q:"What shape has four equal sides?", choices:["Square","Triangle","Circle","Rectangle"], answer:0, d:"easy" },
    { q:"How many letters are in the English alphabet?", choices:["Twenty-four","Twenty-five","Twenty-six","Twenty-seven"], answer:2, d:"easy" },
    { q:"What color are bananas when they are ripe?", choices:["Yellow","Blue","Purple","Black"], answer:0, d:"easy" },
    { q:"What do you call a baby cat?", choices:["Kitten","Puppy","Cub","Foal"], answer:0, d:"easy" },
    { q:"How many days are in a typical, non-leap year?", choices:["360","364","365","366"], answer:2, d:"easy" },
    { q:"What is H2O more commonly known as?", choices:["Water","Salt","Air","Oil"], answer:0, d:"easy" },
    { q:"Which is longer: a kilometer or a meter?", choices:["A kilometer","A meter","They are equal","A centimeter"], answer:0, d:"easy" },
    { q:"Which utensil is used to eat soup?", choices:["Spoon","Fork","Knife","Chopsticks"], answer:0, d:"easy" },
    { q:"How many legs does a spider have?", choices:["Six","Eight","Ten","Twelve"], answer:1, d:"normal" },
    { q:"Which language has the most native speakers in the world?", choices:["Mandarin Chinese","English","Spanish","Hindi"], answer:0, d:"normal" },
    { q:"How many strings does a standard guitar have?", choices:["Four","Five","Six","Seven"], answer:2, d:"normal" },
    { q:"What is the currency of Japan?", choices:["Yen","Won","Yuan","Ringgit"], answer:0, d:"normal" },
    { q:"How many degrees are in a right angle?", choices:["Forty-five","Sixty","Ninety","One hundred eighty"], answer:2, d:"normal" },
    { q:"Who wrote the play 'Romeo and Juliet'?", choices:["William Shakespeare","Charles Dickens","Jane Austen","Leo Tolstoy"], answer:0, d:"normal" },
    { q:"What is the currency used across most of the European Union?", choices:["The Euro","The Pound","The Dollar","The Franc"], answer:0, d:"normal" },
    { q:"How many sides does a hexagon have?", choices:["Five","Six","Seven","Eight"], answer:1, d:"normal" },
    { q:"What is the tallest animal in the world?", choices:["Giraffe","Elephant","Horse","Camel"], answer:0, d:"normal" },
    { q:"Including the repeated note, how many notes are in a do-re-mi octave?", choices:["Five","Seven","Eight","Twelve"], answer:2, d:"normal" },
    { q:"What is the currency of the United Kingdom?", choices:["Pound sterling","Euro","Dollar","Krona"], answer:0, d:"normal" },
    { q:"Who is the author of the 'Harry Potter' book series?", choices:["J.K. Rowling","J.R.R. Tolkien","C.S. Lewis","Roald Dahl"], answer:0, d:"normal" },
    { q:"How many players (sides) are there in a game of chess?", choices:["Two","Three","Four","Six"], answer:0, d:"normal" },
    { q:"What is the largest organ of the human body?", choices:["The skin","The liver","The brain","The heart"], answer:0, d:"normal" },
    { q:"How many colors are on a standard traffic light?", choices:["Two","Three","Four","Five"], answer:1, d:"normal" },
    { q:"What is the official language of France?", choices:["French","English","German","Italian"], answer:0, d:"normal" },
    { q:"The Roman numeral 'X' represents which number?", choices:["Five","Nine","Ten","Fifty"], answer:2, d:"normal" },
    { q:"How many zeros are in the number one thousand?", choices:["Two","Three","Four","Five"], answer:1, d:"normal" },
    { q:"A word that means the same as another word is called a?", choices:["Synonym","Antonym","Homonym","Acronym"], answer:0, d:"normal" },
    { q:"How many hours are in two full days?", choices:["Twenty-four","Thirty-six","Forty-eight","Sixty"], answer:2, d:"normal" },
    { q:"What is the Roman numeral for fifty?", choices:["L","C","D","M"], answer:0, d:"hard" },
    { q:"Who wrote the novel 'War and Peace'?", choices:["Leo Tolstoy","Fyodor Dostoevsky","Anton Chekhov","Alexander Pushkin"], answer:0, d:"hard" },
    { q:"What is the currency of South Korea?", choices:["Won","Yen","Yuan","Baht"], answer:0, d:"hard" },
    { q:"How many sides does a dodecagon have?", choices:["Ten","Eleven","Twelve","Fourteen"], answer:2, d:"hard" },
    { q:"In what year did humans first land on the Moon?", choices:["1959","1965","1969","1972"], answer:2, d:"hard" },
    { q:"What is the SI base unit of mass?", choices:["Kilogram","Gram","Newton","Pound"], answer:0, d:"hard" },
    { q:"Which of these languages is written using the Cyrillic script?", choices:["Russian","French","Greek","Arabic"], answer:0, d:"hard" },
    { q:"Who composed the Ninth Symphony featuring the 'Ode to Joy'?", choices:["Ludwig van Beethoven","Wolfgang Mozart","Johann Bach","Frederic Chopin"], answer:0, d:"hard" },
    { q:"What is the smallest prime number?", choices:["Zero","One","Two","Three"], answer:2, d:"hard" },
    { q:"In a web address, what does 'www' stand for?", choices:["World Wide Web","World Web Wide","Wide World Web","Web World Wide"], answer:0, d:"hard" }
  ],
  "art": [
    { q:"Who painted the Mona Lisa?", choices:["Leonardo da Vinci","Michelangelo","Pablo Picasso","Vincent van Gogh"], answer:0, d:"easy" },
    { q:"What are the three primary colors?", choices:["Red, yellow, blue","Red, green, blue","Orange, purple, green","Black, white, gray"], answer:0, d:"easy" },
    { q:"Which artist famously cut off part of his own ear?", choices:["Vincent van Gogh","Claude Monet","Salvador Dali","Rembrandt"], answer:0, d:"easy" },
    { q:"In which museum is the Mona Lisa displayed?", choices:["The Louvre","The Met","The Uffizi","The Prado"], answer:0, d:"easy" },
    { q:"Who painted the ceiling of the Sistine Chapel?", choices:["Michelangelo","Leonardo da Vinci","Raphael","Donatello"], answer:0, d:"easy" },
    { q:"Who painted 'The Starry Night'?", choices:["Vincent van Gogh","Edvard Munch","Gustav Klimt","Paul Cezanne"], answer:0, d:"easy" },
    { q:"Mixing blue and yellow paint makes which color?", choices:["Green","Orange","Purple","Brown"], answer:0, d:"easy" },
    { q:"The art of folding paper into shapes is called?", choices:["Origami","Calligraphy","Collage","Etching"], answer:0, d:"easy" },
    { q:"A painting of a person is called a?", choices:["Portrait","Landscape","Still life","Mural"], answer:0, d:"easy" },
    { q:"A painting of natural scenery is called a?", choices:["Landscape","Portrait","Abstract","Mosaic"], answer:0, d:"easy" },
    { q:"The art of beautiful, decorative handwriting is called?", choices:["Calligraphy","Origami","Collage","Etching"], answer:0, d:"easy" },
    { q:"Shaping stone, clay, or metal into three-dimensional art is called?", choices:["Sculpture","Painting","Sketching","Printmaking"], answer:0, d:"easy" },
    { q:"Mixing red and white paint makes which color?", choices:["Pink","Purple","Orange","Brown"], answer:0, d:"easy" },
    { q:"Red, orange, and yellow are known as what kind of colors?", choices:["Warm colors","Cool colors","Neutral colors","Primary colors"], answer:0, d:"easy" },
    { q:"Mixing red and yellow paint makes which color?", choices:["Orange","Green","Purple","Brown"], answer:0, d:"easy" },
    { q:"Which tool is most associated with painting?", choices:["Paintbrush","Chisel","Hammer","Pencil"], answer:0, d:"easy" },
    { q:"Crayons and colored pencils are mainly used for?", choices:["Drawing","Welding","Carving","Weaving"], answer:0, d:"easy" },
    { q:"Which of these is a sculpture rather than a painting?", choices:["The Thinker","The Mona Lisa","The Starry Night","The Scream"], answer:0, d:"easy" },
    { q:"In which country did the Renaissance begin?", choices:["Italy","France","Spain","Greece"], answer:0, d:"easy" },
    { q:"Artwork made by gluing materials like paper and fabric onto a surface is a?", choices:["Collage","Fresco","Etching","Mosaic"], answer:0, d:"easy" },
    { q:"Who painted 'The Persistence of Memory', famous for its melting clocks?", choices:["Salvador Dali","Pablo Picasso","Rene Magritte","Joan Miro"], answer:0, d:"normal" },
    { q:"Who painted 'The Scream'?", choices:["Edvard Munch","Gustav Klimt","Egon Schiele","Wassily Kandinsky"], answer:0, d:"normal" },
    { q:"Pablo Picasso is credited with co-founding which art movement?", choices:["Cubism","Surrealism","Impressionism","Expressionism"], answer:0, d:"normal" },
    { q:"Who painted 'Girl with a Pearl Earring'?", choices:["Johannes Vermeer","Rembrandt","Peter Paul Rubens","Frans Hals"], answer:0, d:"normal" },
    { q:"The 'Water Lilies' series was painted by?", choices:["Claude Monet","Edouard Manet","Edgar Degas","Pierre-Auguste Renoir"], answer:0, d:"normal" },
    { q:"Which painting medium uses water-soluble pigments?", choices:["Watercolor","Oil paint","Acrylic","Encaustic"], answer:0, d:"normal" },
    { q:"The Mona Lisa was painted during which period?", choices:["The Renaissance","The Baroque","Romanticism","Modernism"], answer:0, d:"normal" },
    { q:"Which artist is famous for paintings of Campbell's soup cans?", choices:["Andy Warhol","Roy Lichtenstein","Jackson Pollock","Mark Rothko"], answer:0, d:"normal" },
    { q:"Which artist is best known for the drip painting technique?", choices:["Jackson Pollock","Mark Rothko","Willem de Kooning","Barnett Newman"], answer:0, d:"normal" },
    { q:"Who painted 'The Last Supper'?", choices:["Leonardo da Vinci","Michelangelo","Raphael","Sandro Botticelli"], answer:0, d:"normal" },
    { q:"Which movement focused on light and everyday scenes in late-1800s France?", choices:["Impressionism","Cubism","Surrealism","Baroque"], answer:0, d:"normal" },
    { q:"Who painted 'The Birth of Venus'?", choices:["Sandro Botticelli","Titian","Caravaggio","Raphael"], answer:0, d:"normal" },
    { q:"Which Dutch painter created 'The Night Watch' and many self-portraits?", choices:["Rembrandt","Johannes Vermeer","Vincent van Gogh","Piet Mondrian"], answer:0, d:"normal" },
    { q:"A painting done on wet plaster is called a?", choices:["Fresco","Collage","Mosaic","Etching"], answer:0, d:"normal" },
    { q:"Which artist painted the anti-war masterpiece 'Guernica'?", choices:["Pablo Picasso","Salvador Dali","Francisco Goya","Diego Velazquez"], answer:0, d:"normal" },
    { q:"Vincent van Gogh was born in which country?", choices:["The Netherlands","France","Belgium","Germany"], answer:0, d:"normal" },
    { q:"The Sistine Chapel is located in?", choices:["Vatican City","Florence","Venice","Paris"], answer:0, d:"normal" },
    { q:"On the color wheel, which color is the complement of red?", choices:["Green","Blue","Orange","Purple"], answer:0, d:"normal" },
    { q:"Who painted 'American Gothic', showing a farmer holding a pitchfork?", choices:["Grant Wood","Edward Hopper","Norman Rockwell","Andrew Wyeth"], answer:0, d:"normal" },
    { q:"A print made from a design carved into a block of wood is called a?", choices:["Woodcut","Lithograph","Screen print","Monotype"], answer:0, d:"normal" },
    { q:"Who painted 'The Garden of Earthly Delights'?", choices:["Hieronymus Bosch","Pieter Bruegel","Albrecht Durer","Jan van Eyck"], answer:0, d:"hard" },
    { q:"Wassily Kandinsky is regarded as a pioneer of which kind of art?", choices:["Abstract art","Realism","Pop art","Baroque"], answer:0, d:"hard" },
    { q:"Who sculpted 'The Thinker'?", choices:["Auguste Rodin","Gian Lorenzo Bernini","Antonio Canova","Constantin Brancusi"], answer:0, d:"hard" },
    { q:"Who painted 'Las Meninas'?", choices:["Diego Velazquez","Francisco Goya","El Greco","Bartolome Murillo"], answer:0, d:"hard" },
    { q:"The Bauhaus art and design school originated in which country?", choices:["Germany","France","Austria","Switzerland"], answer:0, d:"hard" },
    { q:"Which artist is associated with the 'Blue Period'?", choices:["Pablo Picasso","Henri Matisse","Paul Cezanne","Paul Gauguin"], answer:0, d:"hard" },
    { q:"Who is famous for grid compositions using red, yellow, and blue?", choices:["Piet Mondrian","Kazimir Malevich","Paul Klee","Wassily Kandinsky"], answer:0, d:"hard" },
    { q:"Who painted the 'Arnolfini Portrait'?", choices:["Jan van Eyck","Hans Memling","Hieronymus Bosch","Pieter Bruegel"], answer:0, d:"hard" },
    { q:"Which Mexican artist is renowned for intense personal self-portraits?", choices:["Frida Kahlo","Diego Rivera","Jose Orozco","Rufino Tamayo"], answer:0, d:"hard" },
    { q:"In art, the term 'chiaroscuro' refers to?", choices:["The contrast between light and dark","The folding of paper","A theory of color","A type of brush"], answer:0, d:"hard" }
  ],
  "geography": [
    { q:"What is the capital of France?", choices:["Paris","London","Berlin","Madrid"], answer:0, d:"easy" },
    { q:"Which is the largest ocean on Earth?", choices:["Pacific","Atlantic","Indian","Arctic"], answer:0, d:"easy" },
    { q:"What is the capital of Japan?", choices:["Tokyo","Beijing","Seoul","Bangkok"], answer:0, d:"easy" },
    { q:"The Sahara Desert is located on which continent?", choices:["Africa","Asia","Australia","South America"], answer:0, d:"easy" },
    { q:"What is the capital of Italy?", choices:["Rome","Milan","Venice","Naples"], answer:0, d:"easy" },
    { q:"Which country is shaped like a boot?", choices:["Italy","Spain","Greece","Portugal"], answer:0, d:"easy" },
    { q:"What is the capital of England?", choices:["London","Manchester","Liverpool","Birmingham"], answer:0, d:"easy" },
    { q:"Mount Everest is located in which mountain range?", choices:["The Himalayas","The Andes","The Alps","The Rockies"], answer:0, d:"easy" },
    { q:"On which continent do kangaroos naturally live?", choices:["Australia","Africa","Asia","Europe"], answer:0, d:"easy" },
    { q:"What is the capital of the United States?", choices:["Washington, D.C.","New York","Los Angeles","Chicago"], answer:0, d:"easy" },
    { q:"Which is the largest country in the world by area?", choices:["Russia","Canada","China","USA"], answer:0, d:"easy" },
    { q:"What is the capital of Spain?", choices:["Madrid","Barcelona","Seville","Valencia"], answer:0, d:"easy" },
    { q:"The Great Barrier Reef is off the coast of which country?", choices:["Australia","Brazil","Mexico","Indonesia"], answer:0, d:"easy" },
    { q:"Egypt is located mostly on which continent?", choices:["Africa","Asia","Europe","South America"], answer:0, d:"easy" },
    { q:"What is the capital of Germany?", choices:["Berlin","Munich","Hamburg","Frankfurt"], answer:0, d:"easy" },
    { q:"Which ocean is on the west coast of the United States?", choices:["Pacific","Atlantic","Indian","Arctic"], answer:0, d:"easy" },
    { q:"How many continents are there on Earth?", choices:["Five","Six","Seven","Eight"], answer:2, d:"easy" },
    { q:"What is the capital of Canada?", choices:["Ottawa","Toronto","Vancouver","Montreal"], answer:0, d:"easy" },
    { q:"The Eiffel Tower is located in which country?", choices:["France","Italy","England","Belgium"], answer:0, d:"easy" },
    { q:"Which is the largest hot desert in the world?", choices:["The Sahara","The Gobi","The Kalahari","The Arabian"], answer:0, d:"easy" },
    { q:"What is the capital of Australia?", choices:["Canberra","Sydney","Melbourne","Perth"], answer:0, d:"normal" },
    { q:"Which river runs through Paris?", choices:["The Seine","The Thames","The Rhine","The Danube"], answer:0, d:"normal" },
    { q:"What is the capital of Brazil?", choices:["Brasilia","Rio de Janeiro","Sao Paulo","Salvador"], answer:0, d:"normal" },
    { q:"Mount Kilimanjaro is located in which country?", choices:["Tanzania","Kenya","Ethiopia","Uganda"], answer:0, d:"normal" },
    { q:"Which is currently the most populous country in the world?", choices:["India","China","USA","Indonesia"], answer:0, d:"normal" },
    { q:"The Amazon rainforest is primarily located in which country?", choices:["Brazil","Peru","Colombia","Venezuela"], answer:0, d:"normal" },
    { q:"What is the capital of Russia?", choices:["Moscow","Saint Petersburg","Kyiv","Minsk"], answer:0, d:"normal" },
    { q:"Which mountain range is traditionally used to separate Europe and Asia?", choices:["The Urals","The Alps","The Caucasus","The Carpathians"], answer:0, d:"normal" },
    { q:"What is the capital of Egypt?", choices:["Cairo","Alexandria","Giza","Luxor"], answer:0, d:"normal" },
    { q:"Which strait separates Europe from Africa near Gibraltar?", choices:["The Strait of Gibraltar","The Bosphorus","The Strait of Hormuz","The Strait of Malacca"], answer:0, d:"normal" },
    { q:"What is the capital of China?", choices:["Beijing","Shanghai","Hong Kong","Guangzhou"], answer:0, d:"normal" },
    { q:"Which is the smallest country in the world?", choices:["Vatican City","Monaco","San Marino","Liechtenstein"], answer:0, d:"normal" },
    { q:"Which country has a major city split between Europe and Asia by the Bosphorus?", choices:["Turkey","Russia","Greece","Egypt"], answer:0, d:"normal" },
    { q:"What is the capital of India?", choices:["New Delhi","Mumbai","Kolkata","Bangalore"], answer:0, d:"normal" },
    { q:"Which sea lies between Europe and Africa?", choices:["The Mediterranean","The Red Sea","The Black Sea","The Caspian Sea"], answer:0, d:"normal" },
    { q:"The Andes mountains run along which continent?", choices:["South America","Africa","Asia","North America"], answer:0, d:"normal" },
    { q:"What is the capital of South Korea?", choices:["Seoul","Busan","Incheon","Pyongyang"], answer:0, d:"normal" },
    { q:"Which African country is commonly cited as never having been colonized?", choices:["Ethiopia","Kenya","Ghana","Nigeria"], answer:0, d:"normal" },
    { q:"Lake Baikal, the world's deepest lake, is located in which country?", choices:["Russia","Mongolia","China","Kazakhstan"], answer:0, d:"normal" },
    { q:"What is the capital of Argentina?", choices:["Buenos Aires","Santiago","Lima","Montevideo"], answer:0, d:"normal" },
    { q:"What is the capital of Kazakhstan?", choices:["Astana","Almaty","Tashkent","Bishkek"], answer:0, d:"hard" },
    { q:"Counting its overseas territories, which country has the most time zones?", choices:["France","Russia","USA","China"], answer:0, d:"hard" },
    { q:"The Atacama, the driest non-polar desert, is in which country?", choices:["Chile","Peru","Bolivia","Argentina"], answer:0, d:"hard" },
    { q:"Which is the largest island in the world?", choices:["Greenland","New Guinea","Borneo","Madagascar"], answer:0, d:"hard" },
    { q:"The Strait of Hormuz connects the Persian Gulf to which body of water?", choices:["The Gulf of Oman","The Red Sea","The Black Sea","The Caspian Sea"], answer:0, d:"hard" },
    { q:"What is the capital of Mongolia?", choices:["Ulaanbaatar","Astana","Bishkek","Tashkent"], answer:0, d:"hard" },
    { q:"Aconcagua, the highest peak in the Americas, is located in which country?", choices:["Argentina","Chile","Peru","Bolivia"], answer:0, d:"hard" },
    { q:"The Mariana Trench, the deepest ocean trench, is in which ocean?", choices:["The Pacific","The Atlantic","The Indian","The Southern"], answer:0, d:"hard" },
    { q:"What is the capital of New Zealand?", choices:["Wellington","Auckland","Christchurch","Hamilton"], answer:0, d:"hard" },
    { q:"Which country has the longest coastline in the world?", choices:["Canada","Russia","Indonesia","Australia"], answer:0, d:"hard" }
  ],
  "sports": [
    { q:"How many players from each team are on the field in soccer?", choices:["Nine","Ten","Eleven","Twelve"], answer:2, d:"easy" },
    { q:"In which sport do you score a 'touchdown'?", choices:["American football","Basketball","Baseball","Hockey"], answer:0, d:"easy" },
    { q:"How many rings are on the Olympic flag?", choices:["Three","Four","Five","Six"], answer:2, d:"easy" },
    { q:"In tennis, what is a score of zero called?", choices:["Love","Nil","Duck","Zip"], answer:0, d:"easy" },
    { q:"Which sport features a 'slam dunk'?", choices:["Basketball","Volleyball","Tennis","Golf"], answer:0, d:"easy" },
    { q:"How many players from each team are on a basketball court?", choices:["Four","Five","Six","Seven"], answer:1, d:"easy" },
    { q:"Which sport uses a racket and a shuttlecock?", choices:["Badminton","Tennis","Squash","Table tennis"], answer:0, d:"easy" },
    { q:"In golf, what is one stroke under par on a hole called?", choices:["Birdie","Eagle","Bogey","Par"], answer:0, d:"easy" },
    { q:"How many points is a touchdown worth before the extra point?", choices:["Three","Six","Seven","Two"], answer:1, d:"easy" },
    { q:"Which sport is played at Wimbledon?", choices:["Tennis","Golf","Cricket","Rugby"], answer:0, d:"easy" },
    { q:"What is it called when a soccer player scores three goals in a match?", choices:["Hat-trick","Triple","Treble play","Strike"], answer:0, d:"easy" },
    { q:"What piece of equipment do you hit a baseball with?", choices:["A bat","A racket","A club","A stick"], answer:0, d:"easy" },
    { q:"How often are the Summer Olympic Games held?", choices:["Every two years","Every three years","Every four years","Every five years"], answer:2, d:"easy" },
    { q:"Which sport involves a pommel horse and still rings?", choices:["Gymnastics","Wrestling","Boxing","Fencing"], answer:0, d:"easy" },
    { q:"Which sport uses a stick and a puck on ice?", choices:["Ice hockey","Field hockey","Lacrosse","Curling"], answer:0, d:"easy" },
    { q:"How many holes are played in a full round of golf?", choices:["Nine","Twelve","Eighteen","Twenty-four"], answer:2, d:"easy" },
    { q:"Usain Bolt is famous for which sport?", choices:["Sprinting","Swimming","Cycling","Boxing"], answer:0, d:"easy" },
    { q:"Which sport uses the terms 'serve', 'ace', and 'deuce'?", choices:["Tennis","Soccer","Cricket","Golf"], answer:0, d:"easy" },
    { q:"In boxing, what does 'KO' stand for?", choices:["Knockout","Kick-off","Key-out","Knock-over"], answer:0, d:"easy" },
    { q:"Which sport is associated with the Tour de France?", choices:["Cycling","Running","Sailing","Skiing"], answer:0, d:"easy" },
    { q:"How many players are on a cricket team?", choices:["Nine","Ten","Eleven","Twelve"], answer:2, d:"normal" },
    { q:"In which country were the first modern Olympic Games held in 1896?", choices:["Greece","France","England","Italy"], answer:0, d:"normal" },
    { q:"Which country has won the most men's FIFA World Cup titles?", choices:["Brazil","Germany","Italy","Argentina"], answer:0, d:"normal" },
    { q:"In basketball, how many points is a shot from beyond the arc worth?", choices:["One","Two","Three","Four"], answer:2, d:"normal" },
    { q:"Which tennis Grand Slam is played on clay courts?", choices:["The French Open","Wimbledon","The US Open","The Australian Open"], answer:0, d:"normal" },
    { q:"A marathon is approximately how long?", choices:["21 km","42 km","50 km","100 km"], answer:1, d:"normal" },
    { q:"In which sport is the Stanley Cup awarded?", choices:["Ice hockey","Basketball","Baseball","Soccer"], answer:0, d:"normal" },
    { q:"How many players from each team are on a volleyball court?", choices:["Five","Six","Seven","Eight"], answer:1, d:"normal" },
    { q:"The Ryder Cup is contested in which sport?", choices:["Golf","Tennis","Sailing","Cricket"], answer:0, d:"normal" },
    { q:"The Super Bowl is the championship game of which sport?", choices:["American football","Baseball","Basketball","Hockey"], answer:0, d:"normal" },
    { q:"Which boxer was known as 'The Greatest'?", choices:["Muhammad Ali","Mike Tyson","Joe Frazier","George Foreman"], answer:0, d:"normal" },
    { q:"In Formula 1, which flag signals the end of a race?", choices:["The chequered flag","The yellow flag","The red flag","The green flag"], answer:0, d:"normal" },
    { q:"How many tennis Grand Slam tournaments are held each year?", choices:["Three","Four","Five","Six"], answer:1, d:"normal" },
    { q:"The Wimbledon tennis tournament is hosted in which country?", choices:["England","USA","Australia","France"], answer:0, d:"normal" },
    { q:"In baseball, how many strikes make an out?", choices:["Two","Three","Four","Five"], answer:1, d:"normal" },
    { q:"The terms 'birdie' and 'bogey' are used in which sport?", choices:["Golf","Tennis","Bowling","Darts"], answer:0, d:"normal" },
    { q:"The FIFA World Cup is held every how many years?", choices:["Two","Three","Four","Five"], answer:2, d:"normal" },
    { q:"In which sport would you score a 'try'?", choices:["Rugby","Soccer","Hockey","Cricket"], answer:0, d:"normal" },
    { q:"The NBA is a professional league for which sport?", choices:["Basketball","Baseball","American football","Hockey"], answer:0, d:"normal" },
    { q:"What color jersey does the overall leader of the Tour de France wear?", choices:["Yellow","Green","Polka dot","White"], answer:0, d:"normal" },
    { q:"Which country won the first ever FIFA World Cup in 1930?", choices:["Uruguay","Brazil","Italy","Argentina"], answer:0, d:"hard" },
    { q:"In golf, what term describes two strokes under par on a hole?", choices:["Eagle","Birdie","Albatross","Bogey"], answer:0, d:"hard" },
    { q:"What is the highest possible break in snooker without fouls?", choices:["100","147","155","180"], answer:1, d:"hard" },
    { q:"Which city hosted the first modern Summer Olympics in 1896?", choices:["Athens","Paris","London","Rome"], answer:0, d:"hard" },
    { q:"In ten-pin bowling, what is the term for three strikes in a row?", choices:["A turkey","An eagle","A hat-trick","A triple"], answer:0, d:"hard" },
    { q:"The Ashes cricket series is contested between England and which country?", choices:["Australia","India","South Africa","New Zealand"], answer:0, d:"hard" },
    { q:"What is the maximum checkout score with three darts in a single turn?", choices:["150","167","170","180"], answer:2, d:"hard" },
    { q:"How many players are on the field for one team in rugby union?", choices:["Eleven","Thirteen","Fifteen","Eighteen"], answer:2, d:"hard" },
    { q:"In which sport is the Davis Cup awarded?", choices:["Tennis","Golf","Rowing","Cycling"], answer:0, d:"hard" },
    { q:"The 'Fosbury Flop' is a technique used in which athletics event?", choices:["High jump","Long jump","Pole vault","Javelin"], answer:0, d:"hard" }
  ],
  "history": [
    { q:"Who was the first President of the United States?", choices:["George Washington","Abraham Lincoln","Thomas Jefferson","John Adams"], answer:0, d:"easy" },
    { q:"In which year did World War II end?", choices:["1939","1942","1945","1950"], answer:2, d:"easy" },
    { q:"The Great Pyramids are located in which country?", choices:["Egypt","Greece","Mexico","Iraq"], answer:0, d:"easy" },
    { q:"Who was the British Prime Minister during most of World War II?", choices:["Winston Churchill","Neville Chamberlain","Clement Attlee","Margaret Thatcher"], answer:0, d:"easy" },
    { q:"Which ship famously sank in 1912 after hitting an iceberg?", choices:["Titanic","Lusitania","Britannic","Bismarck"], answer:0, d:"easy" },
    { q:"The ancient Roman Empire was centered on which city?", choices:["Rome","Athens","Cairo","Istanbul"], answer:0, d:"easy" },
    { q:"Who is credited with reaching the Americas for Europe in 1492?", choices:["Christopher Columbus","Ferdinand Magellan","Amerigo Vespucci","James Cook"], answer:0, d:"easy" },
    { q:"In which year did World War I begin?", choices:["1900","1914","1918","1920"], answer:1, d:"easy" },
    { q:"Which wall divided a German city until 1989?", choices:["The Berlin Wall","The Great Wall","Hadrian's Wall","The Western Wall"], answer:0, d:"easy" },
    { q:"The U.S. Declaration of Independence was signed in which year?", choices:["1066","1776","1812","1865"], answer:1, d:"easy" },
    { q:"Who led India's nonviolent independence movement?", choices:["Mahatma Gandhi","Jawaharlal Nehru","Subhas Chandra Bose","Vallabhbhai Patel"], answer:0, d:"easy" },
    { q:"Ancient Egyptians wrote using a script of pictures called?", choices:["Hieroglyphics","Cuneiform","Latin","Runes"], answer:0, d:"easy" },
    { q:"Which country gifted the Statue of Liberty to the United States?", choices:["France","England","Spain","Italy"], answer:0, d:"easy" },
    { q:"Which U.S. president was assassinated in Dallas in 1963?", choices:["John F. Kennedy","Abraham Lincoln","Martin Luther King Jr.","Ronald Reagan"], answer:0, d:"easy" },
    { q:"The Cold War was primarily between the USA and which country?", choices:["The Soviet Union","China","Germany","Japan"], answer:0, d:"easy" },
    { q:"Which ancient civilization built the Colosseum?", choices:["The Romans","The Greeks","The Egyptians","The Persians"], answer:0, d:"easy" },
    { q:"Which queen of ancient Egypt was linked with Caesar and Mark Antony?", choices:["Cleopatra","Nefertiti","Hatshepsut","Isis"], answer:0, d:"easy" },
    { q:"The Industrial Revolution began in which country?", choices:["Great Britain","The USA","France","Germany"], answer:0, d:"easy" },
    { q:"Who delivered the 'I Have a Dream' speech?", choices:["Martin Luther King Jr.","Malcolm X","Rosa Parks","Nelson Mandela"], answer:0, d:"easy" },
    { q:"The Vikings came from which region of Europe?", choices:["Scandinavia","The Balkans","Iberia","The British Isles"], answer:0, d:"easy" },
    { q:"Who was the first person to walk on the Moon?", choices:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","Michael Collins"], answer:0, d:"normal" },
    { q:"Which empire was ruled by Genghis Khan?", choices:["The Mongol Empire","The Ottoman Empire","The Roman Empire","The Persian Empire"], answer:0, d:"normal" },
    { q:"In which year did the French Revolution begin?", choices:["1776","1789","1804","1815"], answer:1, d:"normal" },
    { q:"Who was the leader of Nazi Germany?", choices:["Adolf Hitler","Benito Mussolini","Joseph Stalin","Francisco Franco"], answer:0, d:"normal" },
    { q:"The Magna Carta was signed in which country?", choices:["England","France","Germany","Italy"], answer:0, d:"normal" },
    { q:"Which civilization built Machu Picchu?", choices:["The Inca","The Aztec","The Maya","The Olmec"], answer:0, d:"normal" },
    { q:"Who was the first Emperor of Rome?", choices:["Augustus","Julius Caesar","Nero","Constantine"], answer:0, d:"normal" },
    { q:"The Hundred Years' War was fought mainly between England and which country?", choices:["France","Spain","Germany","Scotland"], answer:0, d:"normal" },
    { q:"Which U.S. president issued the Emancipation Proclamation?", choices:["Abraham Lincoln","George Washington","Ulysses S. Grant","Thomas Jefferson"], answer:0, d:"normal" },
    { q:"Pearl Harbor was attacked by which country in 1941?", choices:["Japan","Germany","Italy","China"], answer:0, d:"normal" },
    { q:"The Renaissance began in which country?", choices:["Italy","France","England","Greece"], answer:0, d:"normal" },
    { q:"Which woman ruled ancient Egypt as a pharaoh and king?", choices:["Hatshepsut","Cleopatra","Nefertiti","Nefertari"], answer:0, d:"normal" },
    { q:"The Ottoman Empire was centered in which modern-day country?", choices:["Turkey","Greece","Egypt","Iran"], answer:0, d:"normal" },
    { q:"Which war was fought between the North and South of the United States?", choices:["The Civil War","The Revolutionary War","The War of 1812","The Mexican War"], answer:0, d:"normal" },
    { q:"Which explorer led the first expedition to circumnavigate the globe?", choices:["Ferdinand Magellan","Christopher Columbus","Vasco da Gama","Francis Drake"], answer:0, d:"normal" },
    { q:"The Black Death of the 14th century was a pandemic of which disease?", choices:["The plague","Smallpox","Cholera","Influenza"], answer:0, d:"normal" },
    { q:"Which country was ruled by Louis XIV, the 'Sun King'?", choices:["France","Spain","England","Austria"], answer:0, d:"normal" },
    { q:"The ancient Olympic Games originated in which country?", choices:["Greece","Italy","Egypt","Turkey"], answer:0, d:"normal" },
    { q:"Who was the Soviet leader during the Cuban Missile Crisis?", choices:["Nikita Khrushchev","Joseph Stalin","Leonid Brezhnev","Vladimir Lenin"], answer:0, d:"normal" },
    { q:"In which year did the Berlin Wall fall?", choices:["1985","1989","1991","1993"], answer:1, d:"normal" },
    { q:"Who was crowned the first Holy Roman Emperor in 800 AD?", choices:["Charlemagne","Otto I","Frederick Barbarossa","Constantine"], answer:0, d:"hard" },
    { q:"The Treaty of Versailles was signed in which year?", choices:["1918","1919","1920","1921"], answer:1, d:"hard" },
    { q:"Which ancient wonder stood in the harbor of Alexandria?", choices:["The Lighthouse of Alexandria","The Colossus of Rhodes","The Hanging Gardens","The Temple of Artemis"], answer:0, d:"hard" },
    { q:"Who was the last Tsar of Russia?", choices:["Nicholas II","Alexander III","Peter the Great","Ivan IV"], answer:0, d:"hard" },
    { q:"The Battle of Hastings took place in which year?", choices:["1066","1215","1314","1485"], answer:0, d:"hard" },
    { q:"Which dynasty built most of the Great Wall of China as it appears today?", choices:["The Ming","The Qing","The Han","The Tang"], answer:0, d:"hard" },
    { q:"Hannibal crossed the Alps with elephants to attack which empire?", choices:["Rome","Greece","Egypt","Persia"], answer:0, d:"hard" },
    { q:"The Peloponnesian War was fought between Athens and which city-state?", choices:["Sparta","Thebes","Corinth","Troy"], answer:0, d:"hard" },
    { q:"Which Byzantine emperor codified Roman law in the Corpus Juris Civilis?", choices:["Justinian I","Constantine","Heraclius","Basil II"], answer:0, d:"hard" },
    { q:"In which year did the Russian October Revolution occur?", choices:["1905","1917","1922","1924"], answer:1, d:"hard" }
  ]
};
