/* ============================================================
   Trivia Quest — categories + question bank
   Each question: { q, choices:[4], answer:index, d:'easy'|'medium'|'hard' }
   ============================================================ */
window.CATEGORIES = [
  { id:'science',       name:'Science',        color:'#39C16C', art:'assets/art/characters/science.svg',       blurb:'Atoms, space & the natural world' },
  { id:'entertainment', name:'Entertainment',  color:'#EC4B57', art:'assets/art/characters/entertainment.svg', blurb:'Movies, music & pop culture' },
  { id:'arts',          name:'Arts & Lit',     color:'#A45BD6', art:'assets/art/characters/arts.svg',          blurb:'Painters, authors & masterpieces' },
  { id:'geography',     name:'Geography',      color:'#2E9BD6', art:'assets/art/characters/geography.svg',     blurb:'Capitals, rivers & far-off places' },
  { id:'sports',        name:'Sports',         color:'#F3973F', art:'assets/art/characters/sports.svg',        blurb:'Champions, rules & records' },
  { id:'history',       name:'History',        color:'#F4C63E', art:'assets/art/characters/history.svg',       blurb:'Empires, leaders & turning points' },
];

window.QUESTION_BANK = {
  science: [
    { q:'What is the chemical symbol for gold?', choices:['Au','Ag','Gd','Go'], answer:0, d:'easy' },
    { q:'How many bones are in the adult human body?', choices:['206','201','212','189'], answer:0, d:'easy' },
    { q:'Which planet is known as the Red Planet?', choices:['Mars','Venus','Jupiter','Mercury'], answer:0, d:'easy' },
    { q:'What gas do plants mainly absorb from the air?', choices:['Carbon dioxide','Oxygen','Nitrogen','Hydrogen'], answer:0, d:'easy' },
    { q:'What is the hardest known natural material?', choices:['Diamond','Quartz','Iron','Granite'], answer:0, d:'easy' },
    { q:'Water is made of hydrogen and which element?', choices:['Oxygen','Carbon','Nitrogen','Helium'], answer:0, d:'easy' },
    { q:'What force keeps the planets in orbit around the Sun?', choices:['Gravity','Magnetism','Friction','Inertia'], answer:0, d:'easy' },
    { q:'Which part of the cell is called its "powerhouse"?', choices:['Mitochondria','Nucleus','Ribosome','Membrane'], answer:0, d:'medium' },
    { q:'Which element has the atomic number 1?', choices:['Hydrogen','Helium','Oxygen','Carbon'], answer:0, d:'medium' },
    { q:'What is the most abundant gas in Earth’s atmosphere?', choices:['Nitrogen','Oxygen','Carbon dioxide','Argon'], answer:0, d:'medium' },
    { q:'Who developed the theory of general relativity?', choices:['Albert Einstein','Isaac Newton','Niels Bohr','Galileo'], answer:0, d:'medium' },
    { q:'Approximately how fast does light travel in a vacuum?', choices:['300,000 km/s','30,000 km/s','3,000 km/s','3 million km/s'], answer:0, d:'hard' },
  ],
  entertainment: [
    { q:'Who played Jack in the 1997 film "Titanic"?', choices:['Leonardo DiCaprio','Brad Pitt','Tom Cruise','Johnny Depp'], answer:0, d:'easy' },
    { q:'What is the wizarding school in "Harry Potter"?', choices:['Hogwarts','Durmstrang','Beauxbatons','Ilvermorny'], answer:0, d:'easy' },
    { q:'Which band performed "Bohemian Rhapsody"?', choices:['Queen','The Beatles','Led Zeppelin','The Who'], answer:0, d:'easy' },
    { q:'In "Star Wars", what is the name of Han Solo’s ship?', choices:['Millennium Falcon','X-Wing','Slave I','Star Destroyer'], answer:0, d:'easy' },
    { q:'Which superhero is known as the "Dark Knight"?', choices:['Batman','Superman','Spider-Man','Iron Man'], answer:0, d:'easy' },
    { q:'Which series features a place called the "Upside Down"?', choices:['Stranger Things','Dark','The OA','Wednesday'], answer:0, d:'easy' },
    { q:'Which artist released the album "Thriller"?', choices:['Michael Jackson','Prince','Stevie Wonder','Lionel Richie'], answer:0, d:'easy' },
    { q:'In which city is the sitcom "Friends" set?', choices:['New York','Los Angeles','Chicago','Boston'], answer:0, d:'easy' },
    { q:'Who is the author of the "Game of Thrones" novels?', choices:['George R. R. Martin','J. R. R. Tolkien','Stephen King','Brandon Sanderson'], answer:0, d:'medium' },
    { q:'Who voiced Woody in "Toy Story"?', choices:['Tom Hanks','Tim Allen','Billy Crystal','Robin Williams'], answer:0, d:'medium' },
    { q:'Who directed "Jurassic Park" (1993)?', choices:['Steven Spielberg','James Cameron','George Lucas','Ridley Scott'], answer:0, d:'medium' },
    { q:'Which film won the first ever Academy Award for Best Picture?', choices:['Wings','Sunrise','The Jazz Singer','Metropolis'], answer:0, d:'hard' },
  ],
  arts: [
    { q:'Who painted the "Mona Lisa"?', choices:['Leonardo da Vinci','Michelangelo','Raphael','Donatello'], answer:0, d:'easy' },
    { q:'Who wrote "Romeo and Juliet"?', choices:['William Shakespeare','Charles Dickens','Jane Austen','Mark Twain'], answer:0, d:'easy' },
    { q:'"The Starry Night" was painted by whom?', choices:['Vincent van Gogh','Claude Monet','Pablo Picasso','Salvador Dalí'], answer:0, d:'easy' },
    { q:'Mixing blue and yellow paint produces which colour?', choices:['Green','Purple','Orange','Brown'], answer:0, d:'easy' },
    { q:'In which city is the Louvre museum?', choices:['Paris','London','Rome','Madrid'], answer:0, d:'easy' },
    { q:'Who wrote "Pride and Prejudice"?', choices:['Jane Austen','Emily Brontë','Virginia Woolf','George Eliot'], answer:0, d:'medium' },
    { q:'The statue of "David" was sculpted by whom?', choices:['Michelangelo','Bernini','Rodin','Donatello'], answer:0, d:'medium' },
    { q:'Which movement is Salvador Dalí most associated with?', choices:['Surrealism','Cubism','Impressionism','Pop Art'], answer:0, d:'medium' },
    { q:'Who painted the ceiling of the Sistine Chapel?', choices:['Michelangelo','Leonardo da Vinci','Raphael','Botticelli'], answer:0, d:'medium' },
    { q:'"War and Peace" was written by whom?', choices:['Leo Tolstoy','Fyodor Dostoevsky','Anton Chekhov','Nikolai Gogol'], answer:0, d:'medium' },
    { q:'Who wrote "The Old Man and the Sea"?', choices:['Ernest Hemingway','John Steinbeck','F. Scott Fitzgerald','William Faulkner'], answer:0, d:'medium' },
    { q:'Which novel famously opens with "Call me Ishmael"?', choices:['Moby-Dick','Dracula','1984','The Odyssey'], answer:0, d:'hard' },
  ],
  geography: [
    { q:'What is the capital of France?', choices:['Paris','London','Berlin','Madrid'], answer:0, d:'easy' },
    { q:'Which is the largest ocean on Earth?', choices:['Pacific','Atlantic','Indian','Arctic'], answer:0, d:'easy' },
    { q:'Which is the largest hot desert in the world?', choices:['Sahara','Gobi','Kalahari','Arabian'], answer:0, d:'easy' },
    { q:'Mount Everest lies in which mountain range?', choices:['Himalayas','Andes','Alps','Rockies'], answer:0, d:'easy' },
    { q:'What is the capital of Japan?', choices:['Tokyo','Kyoto','Osaka','Seoul'], answer:0, d:'easy' },
    { q:'The Great Barrier Reef is off the coast of which country?', choices:['Australia','Brazil','Mexico','Indonesia'], answer:0, d:'easy' },
    { q:'The Amazon rainforest is mostly located in which country?', choices:['Brazil','Peru','Colombia','Venezuela'], answer:0, d:'easy' },
    { q:'Which country has the largest population in the world?', choices:['India','China','United States','Indonesia'], answer:0, d:'medium' },
    { q:'What is the smallest country in the world by area?', choices:['Vatican City','Monaco','Malta','San Marino'], answer:0, d:'medium' },
    { q:'Which US state is the largest by area?', choices:['Alaska','Texas','California','Montana'], answer:0, d:'medium' },
    { q:'What is the capital of Canada?', choices:['Ottawa','Toronto','Vancouver','Montreal'], answer:0, d:'medium' },
    { q:'Which African country was formerly known as Abyssinia?', choices:['Ethiopia','Sudan','Kenya','Somalia'], answer:0, d:'hard' },
  ],
  sports: [
    { q:'How many players from one team are on a soccer field?', choices:['11','9','10','12'], answer:0, d:'easy' },
    { q:'In which sport would you perform a "slam dunk"?', choices:['Basketball','Volleyball','Tennis','Hockey'], answer:0, d:'easy' },
    { q:'How often are the Summer Olympic Games normally held?', choices:['Every 4 years','Every 2 years','Every 3 years','Every 5 years'], answer:0, d:'easy' },
    { q:'Which Grand Slam tennis event is played on grass in London?', choices:['Wimbledon','US Open','French Open','Australian Open'], answer:0, d:'easy' },
    { q:'How many rings are on the Olympic flag?', choices:['5','4','6','3'], answer:0, d:'easy' },
    { q:'Which sport uses a shuttlecock?', choices:['Badminton','Squash','Table tennis','Lacrosse'], answer:0, d:'easy' },
    { q:'Usain Bolt is most famous for which sport?', choices:['Sprinting','Swimming','Cycling','Long jump'], answer:0, d:'easy' },
    { q:'How many points is a touchdown worth in American football?', choices:['6','7','3','5'], answer:0, d:'medium' },
    { q:'Which nation has won the most men’s FIFA World Cups?', choices:['Brazil','Germany','Italy','Argentina'], answer:0, d:'medium' },
    { q:'In golf, what is a score of one under par on a hole called?', choices:['Birdie','Eagle','Bogey','Par'], answer:0, d:'medium' },
    { q:'How many rounds are in a standard world-title boxing bout?', choices:['12','10','15','8'], answer:0, d:'medium' },
    { q:'What is the highest possible break in a single frame of snooker?', choices:['147','144','150','155'], answer:0, d:'hard' },
  ],
  history: [
    { q:'In which year did World War II end?', choices:['1945','1944','1939','1950'], answer:0, d:'easy' },
    { q:'Who was the first President of the United States?', choices:['George Washington','Abraham Lincoln','Thomas Jefferson','John Adams'], answer:0, d:'easy' },
    { q:'The Great Wall is located in which country?', choices:['China','Japan','India','Mongolia'], answer:0, d:'easy' },
    { q:'Which explorer reached the Americas in 1492?', choices:['Christopher Columbus','Ferdinand Magellan','Vasco da Gama','James Cook'], answer:0, d:'easy' },
    { q:'Which ancient empire built the Colosseum in Rome?', choices:['Roman','Greek','Ottoman','Persian'], answer:0, d:'easy' },
    { q:'In which year did the Titanic sink?', choices:['1912','1905','1918','1923'], answer:0, d:'medium' },
    { q:'Which Egyptian queen was famously allied with Julius Caesar?', choices:['Cleopatra','Nefertiti','Hatshepsut','Isis'], answer:0, d:'medium' },
    { q:'In which year did the French Revolution begin?', choices:['1789','1776','1799','1804'], answer:0, d:'medium' },
    { q:'Who was the British Prime Minister for most of World War II?', choices:['Winston Churchill','Neville Chamberlain','Clement Attlee','Anthony Eden'], answer:0, d:'medium' },
    { q:'In which year did the Berlin Wall fall?', choices:['1989','1991','1985','1979'], answer:0, d:'medium' },
    { q:'In which year was the US Declaration of Independence adopted?', choices:['1776','1789','1812','1620'], answer:0, d:'medium' },
    { q:'Who led the Soviet Union from the mid-1920s until 1953?', choices:['Joseph Stalin','Vladimir Lenin','Nikita Khrushchev','Leon Trotsky'], answer:0, d:'hard' },
  ],
};
